### ISSUE TITLE
how to Convert source code to the windows with Cygwin

### ISSUE THREAD

**Issue by euphrat1ca** [Xyl2k/Hydra-GUI#3]
well,hello. i'm new to this security-tools. Is there someone could tell me how to Convert source code to the windows. I used the Cygwin with the guide from the internet. But it still have some error.
like this : terminals database is inaccessible

**Comment by Xyl2k** [comment]
i don't understand, your problem, paste the compilation log error please

**Comment by Xyl2k** [comment]
assumed solved
