### ISSUE TITLE
wordlist drag and drop not getting the right path

### ISSUE THREAD

**Issue by xillwillx** [Xyl2k/Hydra-GUI#4]
puts forward slashes and only a partial path, not the full path

**Comment by Xyl2k** [comment]
i don't see the problem

![2017-11-23_18-24-13](https://user-images.githubusercontent.com/8536299/33184236-e5cf14c4-d07b-11e7-9f23-3563256f5774.png)

**Comment by xillwillx** [comment]
This is what I get
![image](https://user-images.githubusercontent.com/2845406/33234179-0e0b52d4-d1f0-11e7-9ba6-fcb693486301.png)

**Comment by Xyl2k** [comment]
okay, try Hydra-GUI_fullpath.zip from the main branch

**Comment by xillwillx** [comment]
Works perfect now. Thanks for the quick update.
